#!/usr/bin/env python3

"""Example of a the simplest workflow that generates and returns an entry (gathering some sysinfo from the host).

    By employing a masking_tag we can redirect the same entry to be generated by the same axs code (mounted)
    in a docker image (and therefore gather different sysinfo).

    The output entry is returned in an "exchange collection", which is pre-created by axs before running docker.

Usage examples:
        # direct on-host execution:
                axs byquery program_output,uname

        # in-docker execution:
                axs byquery program_output_in_docker,uname
"""
